name: abuild
on:
  push:
    branches: [ london, prod ]
  workflow_dispatch:
jobs:
  Dispatcher:
    runs-on: ubuntu-latest
    steps:
    - name: Dispatch to Deploy london
      if: github.ref_name  == 'london'
      uses: actions/github-script@v6
      with:
        github-token: ${{ secrets.ACTIONS_KEY }}
        script: |
          await github.rest.actions.createWorkflowDispatch({
            owner: 'bolaji-kg',
            repo: 'testt',
            workflow_id: 'bdeploy.yml',
            ref: 'london'
            # inputs: {
            #   custom_event_type: 'deploy-trigger'}
          })
    - name: Dispatch to Deploy prod
      if: github.ref_name  == 'prod'
      uses: actions/github-script@v6
      with:
        github-token: ${{ secrets.ACTIONS_KEY }}
        script: |
          await github.rest.actions.createWorkflowDispatch({
            owner: 'bolaji-kg',
            repo: 'testt',
            workflow_id: 'bdeploy.yml',
            ref: 'prod'
          })
