name: bdeploy
on:
 workflow_dispatch:
env:
  GIT_PR_SHA: ${GITHUB_SHA}
  GIT_PR_SHORT: ${GITHUB_SHA:0:10}
jobs:
  Prod-Deploy:
    runs-on: ubuntu-latest
    # if: ${{ github.ref_name  == 'london' && github.event.workflow_run.conclusion == 'success' }}
    steps:
      - run: |
          echo "Triggering Wokflow b"
          export GIT_PR_SHORT=${{ env.GIT_PR_SHORT }}
          echo "GIT SHA $GIT_PR_SHORT"
          echo "gitref ${{github.ref_name}}"
      - name: Checkout
        uses: actions/checkout@v3
  Staging-Deploy:
    runs-on: ubuntu-latest
    # if: ${{ github.ref_name  == 'london' && github.event.workflow_run.conclusion == 'success' }}
    steps:
      - run: |
          echo "Triggering Wokflow b"
          export GIT_PR_SHORT=${{ env.GIT_PR_SHORT }}
          echo "GIT SHA $GIT_PR_SHORT"
      - name: Checkout
        uses: actions/checkout@v3
