name: Workflow B

on:
 workflow_run:
    workflows: ["Workflow A"]
    types:
      - completed
jobs:
  build:
  
    runs-on: ubuntu-latest

    steps:
      - name: Check am
        run: |
         echo "it got to me"
      # Your build steps here
