name: Workflow B

on:
 workflow_run:
    workflows: ["Workflow A"]
    types:
      - completed
env:
  GIT_PR_SHA: ${GITHUB_SHA}
  

jobs:
  build:
    if: ${{ github.ref_name  == 'london' && github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Check am
        run: |
         echo "it got to me"
      - name: 'Download artifact'
        uses: actions/github-script@v6
        with:
          script: |
            let allArtifacts = await github.rest.actions.listWorkflowRunArtifacts({
               owner: context.repo.owner,
               repo: context.repo.repo,
               run_id: context.payload.workflow_run.id,
            });
            let matchArtifact = allArtifacts.data.artifacts.filter((artifact) => {
              return artifact.name == "pr_number"
            })[0];
            let download = await github.rest.actions.downloadArtifact({
               owner: context.repo.owner,
               repo: context.repo.repo,
               artifact_id: matchArtifact.id,
               archive_format: 'zip',
            });
            let fs = require('fs');
            fs.writeFileSync(`${process.env.GITHUB_WORKSPACE}/pr_number.zip`, Buffer.from(download.data));

      - name: 'Unzip artifact'
        run: |
         unzip pr_number.zip
         ls
         cat pr_number
         echo "out"
         export GIT_PR_SHA=${{ env.GIT_PR_SHA }}
         echo "$GIT_PR_SHA"
         


#       - name: 'Comment on PR'
#         uses: actions/github-script@v6
#         with:
#           github-token: ${{ secrets.GITHUB_TOKEN }}
#           script: |
#             let fs = require('fs');
#             let issue_number = Number(fs.readFileSync('./pr_number'));
#             await github.rest.issues.createComment({
#               owner: context.repo.owner,
#               repo: context.repo.repo,
#               issue_number: issue_number,
#               body: 'Thank you for the PR!'
#             });
