name: Workflow A

on:
  push:
    branches:
      - london

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Workflow B
        run: |
         echo "out"
         exit 1
         
      

      
