name: Workflow A

on:
  workflow_dispatch:
  push:
    branches:
      - london
env:
  GIT_PR_SHA: ${GITHUB_SHA}
  GIT_PR_SHORT: ${GITHUB_SHA:0:10}
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Trigger Workflow B
        run: |
         echo "out"
         export GIT_PR_SHORT=${{ env.GIT_PR_SHORT }}
         mkdir -p ./pr
         echo $GIT_PR_SHORT > ./pr/pr_number
         echo "GIT SHA $GIT_PR_SHORT"
         
      - uses: actions/upload-artifact@v3
        with:
          name: pr_number
          path: ./pr/
      

      
